name: flareline_template
description: "Un template Flutter inspiré de FlareLine, personnalisable pour tes projets."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  intl: ^0.20.2
  infinite_scroll_pagination: ^4.0.0
  lucide_icons: ^0.257.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.15 
  http: ^1.1.0
  open_file: 3.5.10
  cupertino_icons: ^1.0.8
  fluentui_system_icons: ^1.1.232
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  fl_chart: ^1.0.0
  audioplayers: ^6.0.0
  vibration: ^1.9.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile.jpg
    - assets/logo1.png
    - assets/logo2.jpeg
    - assets/sounds/notification.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font_poppins/Poppins-Regular.ttf
        - asset: assets/font_poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font_poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font_poppins/Poppins-Light.ttf
          weight: 300
